### ISSUE TITLE
Update Install.yml

### ISSUE THREAD

**Issue by LaMonF** [Ultchad/kalliope-espeak#1]
Please update your install.yml to include dependencies for espeak.

You can use the APT module from [Ansible](http://docs.ansible.com/ansible/apt_module.html)

So we can referece your TTS in doc of the main kalliope project

**Comment by Ultchad** [comment]
I have update my bad dna.yml file and add to install.yml espeak package

Thanks

**Comment by LaMonF** [comment]
Your repo has been added to our community [TTS list](https://github.com/kalliope-project/kalliope/blob/master/Docs/tts_list.md) :)
