### ISSUE TITLE
Kalliope core integration

### ISSUE THREAD

**Issue by Sispheor** [Ultchad/kalliope-espeak#3]
Hi,
I would like to integrate your module in Kalliope core. What do you think?
If it sounds good to you, can you PR your tts into the dev branch?

Thank you very much.

**Comment by Ultchad** [comment]
Yes it would please me
it was my first code on github (and the first steps with git)
I did the Pull request [https://github.com/kalliope-project/kalliope/pull/336](https://github.com/kalliope-project/kalliope/pull/336)

Thanks
